In [1]:
import pandas as pd
from sklearn import preprocessing
from sklearn.preprocessing import Binarizer 

/home/sahibachopra/miniconda/envs/ai/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [2]:
data = pd.read_csv('WA_Fn-UseC_-Sales-Win-Loss.csv')

Binarize labels in a one-vs-all fashion

Several regression and binary classification algorithms are available in scikit-learn. A simple way to extend these algorithms to the multi-class classification case is to use the so-called one-vs-all scheme.

At learning time, this simply consists in learning one regressor or binary classifier per class. In doing so, one needs to convert multi-class labels to binary labels (belong or does not belong to the class). LabelBinarizer makes this process easy with the transform method.

At prediction time, one assigns the class for which the corresponding model gave the greatest confidence. LabelBinarizer makes this easy with the inverse_transform method.

In [3]:
data.head()

Opportunity Number     Supplies Subgroup          Supplies Group  \
0             1641984  Exterior Accessories         Car Accessories   
1             1658010  Exterior Accessories         Car Accessories   
2             1674737      Motorcycle Parts  Performance & Non-auto   
3             1675224         Shelters & RV  Performance & Non-auto   
4             1689785  Exterior Accessories         Car Accessories   

      Region Route To Market  Elapsed Days In Sales Stage Opportunity Result  \
0  Northwest    Fields Sales                           76                Won   
1    Pacific        Reseller                           63               Loss   
2    Pacific        Reseller                           24                Won   
3    Midwest        Reseller                           16               Loss   
4    Pacific        Reseller                           69               Loss   

   Sales Stage Change Count  Total Days Identified Through Closing  \
0                        13                                    104   
1                         2                                    163   
2                         7                                     82   
3                         5                                    124   
4                        11                                     91   

   Total Days Identified Through Qualified  Opportunity Amount USD  \
0                                      101                       0   
1                                      163                       0   
2                                       82                    7750   
3                                      124                       0   
4                                       13                   69756   

   Client Size By Revenue  Client Size By Employee Count  \
0                       5                              5   
1                       3                              5   
2                       1                              1   
3                       1                              1   
4                       1                              1   

   Revenue From Client Past Two Years Competitor Type  \
0                                   0         Unknown   
1                                   0         Unknown   
2                                   0         Unknown   
3                                   0           Known   
4                                   0         Unknown   

   Ratio Days Identified To Total Days  Ratio Days Validated To Total Days  \
0                              0.69636                            0.113985   
1                              0.00000                            1.000000   
2                              1.00000                            0.000000   
3                              1.00000                            0.000000   
4                              0.00000                            0.141125   

   Ratio Days Qualified To Total Days  Deal Size Category  
0                            0.154215                   1  
1                            0.000000                   1  
2                            0.000000                   1  
3                            0.000000                   1  
4                            0.000000                   4

In [4]:
data.groupby('Opportunity Result').size()

Opportunity Result
Loss    60398
Won     17627
dtype: int64

In [7]:
lb = preprocessing.LabelBinarizer()

In [8]:
data['result'] = lb.fit_transform(data['Opportunity Result'])

In [9]:
data.groupby('result').size()

result
0    60398
1    17627
dtype: int64

## with thresholding

In [15]:
data.describe()

Opportunity Number  Elapsed Days In Sales Stage  \
count        7.802500e+04                 78025.000000   
mean         7.653429e+06                    43.595348   
std          1.054848e+06                    26.585600   
min          1.641984e+06                     0.000000   
25%          6.900423e+06                    19.000000   
50%          7.545569e+06                    43.000000   
75%          8.228329e+06                    65.000000   
max          1.009427e+07                   210.000000   

       Sales Stage Change Count  Total Days Identified Through Closing  \
count              78025.000000                           78025.000000   
mean                   2.955732                              16.728356   
std                    1.497242                              16.729593   
min                    1.000000                               0.000000   
25%                    2.000000                               4.000000   
50%                    3.000000                              12.000000   
75%                    3.000000                              24.000000   
max                   23.000000                             208.000000   

       Total Days Identified Through Qualified  Opportunity Amount USD  \
count                             78025.000000            78025.000000   
mean                                 16.314348            91637.260750   
std                                  16.562597           133161.029156   
min                                   0.000000                0.000000   
25%                                   4.000000            15000.000000   
50%                                  12.000000            49000.000000   
75%                                  24.000000           105099.000000   
max                                 208.000000          1000000.000000   

       Client Size By Revenue  Client Size By Employee Count  \
count            78025.000000                   78025.000000   
mean                 1.620481                       1.604050   
std                  1.235796                       1.210744   
min                  1.000000                       1.000000   
25%                  1.000000                       1.000000   
50%                  1.000000                       1.000000   
75%                  1.000000                       1.000000   
max                  5.000000                       5.000000   

       Revenue From Client Past Two Years  \
count                        78025.000000   
mean                             0.303287   
std                              0.930290   
min                              0.000000   
25%                              0.000000   
50%                              0.000000   
75%                              0.000000   
max                              4.000000   

       Ratio Days Identified To Total Days  \
count                         78025.000000   
mean                              0.203063   
std                               0.364985   
min                               0.000000   
25%                               0.000000   
50%                               0.000000   
75%                               0.197225   
max                               1.000000   

       Ratio Days Validated To Total Days  Ratio Days Qualified To Total Days  \
count                        78025.000000                        78025.000000   
mean                             0.488314                            0.185048   
std                              0.448077                            0.340283   
min                              0.000000                            0.000000   
25%                              0.000000                            0.000000   
50%                              0.448000                            0.000000   
75%                              1.000000                            0.188552   
max                              1.000000                            1.000000   

       Deal Size Categ

In [3]:
binarizer_elapsedDays = Binarizer(65)
binarizer_ratioDaysIden = Binarizer(0.19)

In [4]:
elapsedDays = data['Elapsed Days In Sales Stage'].values.reshape(1, -1) 
ratioDaysIden = data['Ratio Days Identified To Total Days'].values.reshape(1, -1)

In [5]:
elapsed_days_binary = binarizer_elapsedDays.fit_transform(elapsedDays)
ratio_days_identified_binary = binarizer_ratioDaysIden.fit_transform(ratioDaysIden)

In [9]:
print ("\nOriginal elapsed days data values : \n",  elapsedDays) 
print ("\nOriginal 'Ratio Days Identified To Total Days' data values : \n",  ratioDaysIden) 
print ("\nBinarized elapsed days : \n", elapsed_days_binary) 
print ("\nBinarized 'Ratio Days Identified To Total Days' : \n", ratio_days_identified_binary) 


Original elapsed days data values : 
 [[76 63 24 ...  0  0  0]]

Original 'Ratio Days Identified To Total Days' data values : 
 [[0.69636 0.      1.      ... 0.      1.      0.     ]]

Binarized elapsed days : 
 [[1 0 0 ... 0 0 0]]

Binarized 'Ratio Days Identified To Total Days' : 
 [[1. 0. 1. ... 0. 1. 0.]]
